version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: |
            gem install bundler -V --no-document -v '2.1.4'
            bundle install
      - run:
          name: Rspec
          command: |
            bundle exec rspec
